# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RequestTest4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RequestTest4
    pod 'Alamofire'
    pod 'SDWebImage'
  target 'RequestTest4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RequestTest4UITests' do
    # Pods for testing
  end

end
